apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8srequiredruntimeclass
spec:
  crd:
    spec:
      names:
        kind: K8sRequiredRuntimeClass
      validation:
        type: object
        properties:
          runtimeClass:
            type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8srequiredruntimeclass

        violation[{"msg": msg}] {
          input.review.object.spec.runtimeClassName == ""
          msg := "Runtime class is required for GPU workloads"
        }
---
apiVersion: config.gatekeeper.sh/v1alpha1
kind: K8sRequiredRuntimeClass
metadata:
  name: require-runtime-class
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces: ["gpu-workloads"]
  parameters:
    runtimeClass: "nvidia"
