apiVersion: v1
kind: ConfigMap
metadata:
  name: version-config
  namespace: cattle-fleet-system
data:
  nvidia:
    operatorTag: "v24.8.0"
    runtimeTag: "12.3.0"
  amd:
    operatorTag: "v0.9.0"
    runtimeTag: "5.6.0"
  intel:
    operatorTag: "v0.3.0"
    runtimeTag: "23.2.0"